# The URL the site will be built for
base_url = "https://freemasen.com"
# Whether to automatically compile all Sass files in the sass directory
compile_sass = true


title = "Free Masen"
description = "A blog about software development"
default_language = "en"
build_search_index = true
generate_feeds = true
feed_filenames = ["atom.xml"]
author = "Robert Masen <r.f.masen@gmail.com>"

[markdown]
highlight_code = true
highlight_theme = "night-owl"
extra_syntaxes_and_themes = ["syntaxes"]

[extra]
# Put all your custom variables here
hyde_links = [
    {url = "/utils", name = "Utils"},
    {url = "/fun", name = "Fun"},
    {url = "/about", name = "About"},
]
hyde_theme = "theme-base-0c"
hyde_sticky = false
