# The URL the site will be built for
base_url = "https://wiredforge.com"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Gutenberg
highlight_code = true
# highlight_theme = "base16-ocean-light"
# highlight_theme = "charcoal"
# highlight_theme = "inspired-github"
# highlight_theme = "subway-madrid"
# highlight_theme = "subway-moscow"

highlight_theme = "material-light"

title = "Wired Forge"
description = "A blog about software development"
language_code = "en"
build_search_index = true
generate_rss = true

[extra]
# Put all your custom variables here