[build]

publish = "public"
command = "zola build"

[context.production]
command = "zola build"

[context.deploy-preview]
command = "zola build -u $DEPLOY_PRIME_URL --drafts"

[environment]
# Set the version name that you want to use and Netlify will automatically use it.
ZOLA_VERSION = "0.17.2"
