[build]

publish = "public"
command = "npm run build && zola build"

[context.production]
command = "npm run build && zola build"

[context.deploy-preview]
command = "npm run build && zola -c ./config.dev.toml build -u $DEPLOY_PRIME_URL --drafts"
