[package]
name = "server"
version = "0.1.0"
authors = ["FreeMasen"]

[dependencies]
hyper = "^0.11"
futures = "^0.1"
lettre = "^0.7"
url = "^1.6"
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"

[dependencies.rusqlite]
version = "0.13.0"
features = ["bundled"]
